[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
formatter = { command = "ruff", args = ["format"] }
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff"
args = ["server"]
